spring.application.name=webjjang_back

server.port=80

spring.datasource.driverClassName=org.mariadb.jdbc.Driver
# 집에서 작업할 때는 localhost로 작업해서 자기 컴퓨터의 DB 사용(실습용으로 작업)
spring.datasource.url=jdbc:mariadb://localhost:3307/webjjang
# 학교에서는 DBA 컴퓨터의 DB 사용해서 팀 프로젝트 개발
#spring.datasource.url=jdbc:mariadb://10.15.21.178:3306/webjjang
spring.datasource.username=webjjang
spring.datasource.password=webjjang

#DB DDL create table 자동
# - create : 이전 테이블 지우고 다시 만든다. 데이터 사라짐(개발)
# - drop : 테이블 지운다. 데이터 사라짐(개발)
# - create-drop : 애플리케이션이 시작하면 만들고 종료될때 지운다.(개발)
# - update : 스키마 변경(alter table). 데이터 유지(개발)
# - validate : 검사만. 데이터 유지(운영)
# - none : DDL에 대해서 아무일도 하지 않다. 데이터 유지(운영)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 토큰 키를 세팅할 때 32바이트 이상의 길이 데이터를 사용해야 한다.
springboot.jwt.secret=around-hub-studio-flature-spring-boot-3!@#

springdoc.api-docs.version=OPENAPI_3_0

# 파일 업로드를 위한 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=c:/Temp